In [3]:

pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.3 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
##python libarary for fast  numerical calculation
##arary ke sath kaam karti hai

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ##this meaan 1 row 5  columns



ValueError: cannot reshape array of size 5 into shape (1,6)

In [ ]:
##2d arary
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
##identitymtrics

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#3vectorised operation
arr = np.array([1,2,3,4,5])
arr1 = np.array([10,20,30,40,50])

print(arr+arr1) ##addition eleemnt wise

print(arr-arr1)

print(arr*arr1)



[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [25]:
##universalfunction

arr =np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [39]:
##slicing

arr = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
print(arr)


print(arr[0])
print(arr[0][0])

##get 7811 12

arr[1:,2:]

##to print 0,1 row
print(arr[0:2])

##to print 3,4,7,8 --- common se pehel;e row ki slicing denge opr uske baad common ki slicking
print(arr[0:2,2:]) ##---0 se 2 row or 2 se end tak column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
1
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


In [ ]:
##modify array emelemt
arr[0,2] = 23
print(arr)




[[ 1  2 23  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
###statistical concepts ---normaliation

data = np.array([1,2,3,4,5])

mean = np.mean(data)
print(mean)

3.0


In [9]:
##logical operstions

import numpy as np

data = np.array([1,2,3,4,5,6,7,8])



data[(data>5) & (data<8)]

array([6, 7])